### ISSUE TITLE
Silverstripe 4.0.0-rc1 support

### ISSUE THREAD

**Issue by gregrogan** [Firesphere/silverstripe-graphql-jwt#12]
Hi,

It looks like the this module was updated this morning to accept the 4.0.0-beta2 dependency. Any chance of including Silverstripe 4.0.0-rc1? Because of this dependency we can't upgrade our project to Silverstripe 4.0.0-rc1 thus use https for the CMS on Silverstripe platform.

Many thanks
Greg (ACC Developer)

**Comment by Firesphere** [comment]
Hey Greg,

This should've been resolved with the latest RC1 release of this module.

**Comment by gregrogan** [comment]
Thanks for making that change - however I see:
firesphere/silverstripe-graphql-jwt 1.0.0-rc1 requires silverstripe/recipe-core 1.1.x-dev
problem is recipe-core 1.1.x-dev requires silverstripe/framework 4.1.x-dev, not 4.0.0-rc1
Any chance of changing recipe-core to be 1.0.0-rc1?

Cheers
Greg.

**Comment by Firesphere** [comment]
Oops, that was not intentional indeed, it should be 1.0

**Comment by gregrogan** [comment]
Thanks - however not quite out of the woods :)
I'm still getting:
Problem 1                                                                                           
    - Installation request for silverstripe/recipe-core 1.0.0-rc1 -> satisfiable by silverstripe/recip
e-core[1.0.0-rc1].                                                                                    
    - firesphere/silverstripe-graphql-jwt 1.0.1-rc1 requires silverstripe/recipe-core 1.0.x-dev -> satisfiable by silverstripe/recipe-core[1.0.x-dev].                                                      
    - Can only install one of: silverstripe/recipe-core[1.0.x-dev, 1.0.0-rc1].                        
    - Installation request for firesphere/silverstripe-graphql-jwt 1.0.1-rc1 -> satisfiable by firesphere/silverstripe-graphql-jwt[1.0.1-rc1]. 

Can it be changed to
"silverstripe/recipe-core": "1.0.0-rc1"

**Comment by Firesphere** [comment]
Fixed with SS4 Stable release
